routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/events/join', function () {
    return view('events.join');
});



Route::resource('events', 'App\Http\Controllers\EventController');
/*
Route::get('/event', function () {
    return view('event');

});
*/
Auth::routes();
Route::get('/events/join/{id}',[App\Http\Controllers\EventController::class, 'join'])->name('events.join');
Route::get('/events/list',[App\Http\Controllers\EventController::class, 'list'])->name('events.list');

Route::patch('/events/{id}',[App\Http\Controllers\EventController::class, 'update'])->name('events.update');

Route::get('/users/join',[App\Http\Controllers\EventController::class, 'join'])->name('users.join');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('admin/home', [App\Http\Controllers\adminHomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');
Route::get('admin/home', [App\Http\Controllers\adminHomeController::class, 'index'])->name('admin.home')->middleware('is_admin');
Route::get('/memberlist', [App\Http\Controllers\adminHomeController::class, 'show'])->name('memberlist');
Route::patch('/editstatus/{id}', [App\Http\Controllers\adminHomeController::class, 'edit'])->name('editstatus');
Route::get('/editstatus/{id}', [App\Http\Controllers\adminHomeController::class, 'update'])->name('editstatus');

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = [
        'ename',
        'descp',
        //protected $table = 'events';
              
    ];
    //public $timestamps=false;  
    
    public function users()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;
Use DB;
use Illuminate\Http\Request;
use App\Models\Event;
use Illuminate\Support\Facades\Redirect;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::all();
        //$events= Event::Latest('id')->get();
        return view('events.index',compact('events'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('events.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        print_r($request->input());
        $events = new Event;
        $events->ename= $request->ename;
        $events->descp= $request->descp;
        echo $events->save();
        return redirect('/events')->with('success', 'New event created!');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
     
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $events =Event::find($id);
        return view('events.edit',compact('events'));

       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
   */
 
    public function update(Request $request, $id)
    {
        $request->validate([
            'ename'=>'required',
            'descp'=>'required'
        ]);


        $events = Event::find($id);
        $events->ename =  $request->get('ename');
        $events->descp = $request->get('descp');
    
        $events->save();

        return redirect('/events')->with('success', 'Event updated!');
    }

   

    public function list()
    {
        $events = Event::all();
        //$events= Event::Latest('id')->get();

        return view ('events.list',compact('events'));


        //return view ('events.list');
    }

    public function join($id)
    {
        
        $users =Event::find($id);
        $users->event()->attach($events);

        return 'Success';
        //return view('events.join',compact('events'));

    }

    /**
     * Remove the specified resource from storage.s
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $events = Event::find($id);
        $events->delete();

        return redirect('/events')->with('success', 'Event deleted!');

    }

   

}

resources/views/events/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="main">
<div class="container1">

    <br/>
<h1>Add New Event</h1>
<br/>
<div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif

<form  action="{{ route('events.store') }}" method="POST">
   @csrf
   
  <div class="form-group">
    <label for="ename">Name:</label>
    <input type="text" class="form-control" name="ename"  placeholder="Enter event name">
    </div> 



<div class="form-group">
  <label for="descp">Description:</label>
  <textarea class="form-control" rows="5" name="descp"></textarea>
</div>
  
  <button type="submit" class="btn btn-primary">Add Event</button>
</form>
</div>
</div>
</html>
@endsection

resources/views/events/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Edit Event</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('events.update', $events->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="ename">Event Name:</label>
                <input type="text" class="form-control" name="ename" value={{ $events->ename }} />
            </div>

            <div class="form-group">
                <label for="descp">Description:</label>
                <textarea class="form-control" rows="5" name="descp" value={{ $events->descp }} /></textarea>
            </div>

           
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/events/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="main"> 
<div class="col-sm-12">

@if(session()->get('success'))
  <div class="alert alert-success">
    {{ session()->get('success') }}  
  </div>
@endif
</div>
         

<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Events</h1>
    </br>
    <div>
    <a style="margin: 19px;" href="/events/create" class="btn btn-primary">Add Event</a>
    </div>  
    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Description</td>

          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
    @foreach($events as $event)
        <tr>
            <td>{{$event->id}}</td>
            <td>{{$event->ename}}</td>
            <td>{{$event->descp}}</td>
            <td>
                <a href="{{ route('events.edit',$event->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
            <form action="{{ route ('events.destroy', $event->id)}}" method="post">
                  @csrf
                  @method('DELETE')
              <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
       
        @endforeach

  
    </tbody>
  </table>
<div>
</div>
</div> 
@endsection

resources/views/events/join.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Edit Event</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('events.edit', $events->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="ename">Event Name:</label>
                <input type="text" class="form-control" name="ename" value={{ $events->ename }} />
            </div>

            <div class="form-group">
                <label for="descp">Description:</label>
                <textarea class="form-control" rows="5" name="descp" value={{ $events->descp }} /></textarea>
            </div>

           
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/events/list.blade.php
@extends('layouts.user')

@section('content')
<div class="main"> 
<div class="col-sm-12">
<h1> Welcome to VVD Website</h1>
</br>
</br>
</br>
<div class="alert alert-success alert-dismissible">
             <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>

                <strong>Welcome!</strong> You are logged in.

            </div>

@if(session()->get('success'))
  <div class="alert alert-success">
    {{ session()->get('success') }}  
  </div>
@endif
</div>
         


 
     
    <div class="card">
                <div class="card-header"><b>Event List</b></div>
                <div class="card-body"> 
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Description</td>

          
        </tr>
    </thead>
    <tbody>
    @foreach($events as $event)
        <tr>
            <td>{{$event->id}}</td>
            <td>{{$event->ename}}</td>
            <td>{{$event->descp}}</td>
            <td>
                <a href="{{ route('events.join',$event->id)}}" class="btn btn-primary">Join</a>
            </td>
            
        </tr>
       
        @endforeach

  
    </tbody>
  </table>
<div>
</div>

@endsection